version: '3.8'

services:
  qdrant:
    image: y0mg/qdrant-raspberry-pi
    container_name: qdrant_memory
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6333/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  arcos-app:
    build:
      context: .
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    container_name: arcos_app
    restart: unless-stopped
    depends_on:
      - qdrant

    env_file: .env

    network_mode: "host"
    privileged: true

    environment:
      # Point to host PulseAudio socket
      - PULSE_SERVER=unix:/run/user/${UID:-1000}/pulse/native
      - PIPEWIRE_SOCKET=/run/user/${UID:-1000}/pipewire-0
      - HOST_UID=${UID:-1000}
      - HOST_GID=${GID:-1000}
      # Disable PulseAudio autospawn (we use host's server)
      - PULSE_NO_AUTOSPAWN=1
      # Disable cookie authentication (use socket permissions instead)
      - PULSE_COOKIE=/dev/null

    volumes:
      - ./src/main/resources/client_secrets.json:/app/src/main/resources/client_secrets.json:ro
      - ./src/main/resources/upmc-model:/app/src/main/resources/upmc-model:ro
      - /var/run/dbus:/var/run/dbus:ro
      
      # Use variable UID consistently
      - /run/user/${UID:-1000}/pipewire-0:/run/user/${UID:-1000}/pipewire-0
      - /run/user/${UID:-1000}/pulse:/run/user/${UID:-1000}/pulse
      
      # Don't mount cookie - rely on socket permissions instead
      
      - /dev/snd:/dev/snd

    devices:
      - /dev/snd:/dev/snd

volumes:
  qdrant_storage:
