version: '3.8'

services:
  # Qdrant service for the vector database
  qdrant:
    image: y0mg/qdrant-raspberry-pi
    platform: linux/arm64
    container_name: qdrant_memory
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    restart: unless-stopped

  # ArCoS Application Service
  arcos-app:
    build: .
    container_name: arcos_app
    restart: unless-stopped
    depends_on:
      - qdrant
      - piper
    env_file: .env
    network_mode: "host"       # you already have this
    privileged: true
    volumes:
      - ./src/main/resources/client_secrets.json:/app/src/main/resources/client_secrets.json:ro
      - ./src/main/resources/upmc-model:/app/src/main/resources/upmc-model:ro
      - /var/run/dbus:/var/run/dbus:ro
      - /run/user/1000/pipewire-0:/run/user/1000/pipewire-0
      - /dev/snd:/dev/snd

  piper:
      image: rhasspy/wyoming-piper:latest    # or linuxserver/piper, artibex/piper-http etc.
      container_name: wyoming_piper
      restart: unless-stopped
      ports:
        - "10200:10200"    # Wyoming protocol port
      volumes:
        - ./piper-data:/data   # models and download dir for piper voices
      command: [ "--voice", "fr_FR-upmc-medium" ]  # optional default voice