version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.11.4-arm64
    container_name: qdrant_memory
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6333/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  faster-whisper:
    build:
      context: ./docker/remote-faster-whisper
    container_name: faster-whisper-container
    ports:
      - "9876:9876"
    restart: unless-stopped

  arcos-app:
    build:
      context: .
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    container_name: arcos_app
    restart: unless-stopped
    depends_on:
      - qdrant
      - faster-whisper

    env_file: .env

    network_mode: "host"
    privileged: true

    environment:
      - PULSE_SERVER=unix:/run/user/${UID:-1000}/pulse/native
      - PIPEWIRE_SOCKET=/run/user/${UID:-1000}/pipewire-0
      - HOST_UID=${UID:-1000}
      - HOST_GID=${GID:-1000}
      - PULSE_NO_AUTOSPAWN=1
      # Variables pour D-Bus (nécessaire pour Bluetooth)
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/${UID:-1000}/bus

    volumes:
      - ./src/main/resources/client_secrets.json:/app/src/main/resources/client_secrets.json:ro
      - ./src/main/resources/upmc-model:/app/src/main/resources/upmc-model:ro
      
      # D-Bus - CRITIQUE pour Bluetooth
      - /var/run/dbus:/var/run/dbus
      - /run/user/${UID:-1000}/bus:/run/user/${UID:-1000}/bus
      
      # PipeWire/PulseAudio
      - /run/user/${UID:-1000}/pipewire-0:/run/user/${UID:-1000}/pipewire-0
      - /run/user/${UID:-1000}/pulse:/run/user/${UID:-1000}/pulse
      
      # Devices audio
      - /dev/snd:/dev/snd
      
      # USB pour périphériques Bluetooth USB
      - /dev/bus/usb:/dev/bus/usb

    devices:
      - /dev/snd:/dev/snd
    
    # Ajouter les groupes nécessaires
    group_add:
      - audio
      - ${BLUETOOTH_GID:-996}  # GID du groupe bluetooth de l'hôte

volumes:
  qdrant_storage:
